# Generated by Django 3.0.2 on 2020-01-26 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='许可证')),
                ('expire_time', models.DateTimeField(verbose_name='过期时间')),
                ('count', models.IntegerField(default=1, verbose_name='token计数')),
                ('enduring', models.BooleanField(default=False, verbose_name='是否长效登录')),
            ],
            options={
                'verbose_name': 'tokens',
                'verbose_name_plural': 'tokens',
                'db_table': 'tokens',
            },
        ),
    ]
