# Generated by Django 3.0.2 on 2020-01-21 00:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='酒店名称')),
                ('content', models.CharField(max_length=100, null=True, verbose_name='备注')),
                ('location', models.TextField(verbose_name='酒店地址')),
            ],
            options={
                'verbose_name': '酒店管理',
                'verbose_name_plural': '酒店管理',
                'db_table': 'hotels',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('name', models.CharField(max_length=10, verbose_name='房间类型名称')),
                ('content', models.TextField(null=True, verbose_name='详细描述')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Hotel', verbose_name='所属酒店')),
            ],
            options={
                'verbose_name': '房间类型',
                'verbose_name_plural': '房间类型',
                'db_table': 'room_type',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('numer', models.CharField(max_length=10, verbose_name='房间号')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='房间名')),
                ('content', models.TextField(null=True, verbose_name='备注')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Hotel', verbose_name='酒店')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.RoomType', verbose_name='房间类型')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'db_table': 'room',
            },
        ),
    ]
