# Generated by Django 3.0.2 on 2020-01-26 15:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='酒店名称')),
                ('content', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('location', models.TextField(verbose_name='酒店地址')),
            ],
            options={
                'verbose_name': '酒店管理',
                'verbose_name_plural': '酒店管理',
                'db_table': 'hotels',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('number', models.CharField(max_length=10, verbose_name='房间号')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='房间名')),
                ('content', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('room_type_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='房间类型名称')),
                ('room_type_content', models.TextField(blank=True, null=True, verbose_name='房间类型详细描述')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Hotel', verbose_name='酒店')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='HotelFaceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('face_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faces.FaceGroup', verbose_name='人员库')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Hotel', verbose_name='酒店')),
            ],
            options={
                'verbose_name': '酒店 - 人脸库',
                'verbose_name_plural': '酒店 - 人脸库',
                'db_table': 'hotel_face_group',
            },
        ),
    ]
