# Generated by Django 3.0.2 on 2020-01-21 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0003_userface'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelFaceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('face_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faces.FaceGroup', verbose_name='人员库')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Hotel', verbose_name='酒店')),
            ],
            options={
                'verbose_name': '酒店 - 人脸库',
                'verbose_name_plural': '酒店 - 人脸库',
                'db_table': 'hotel_face_group',
            },
        ),
    ]
