# Generated by Django 3.0.2 on 2020-02-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='imgs',
            field=models.TextField(default='', verbose_name='图片集'),
        ),
    ]
