# Generated by Django 3.0.2 on 2020-02-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_hotel_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ambitus',
            field=models.TextField(default='', verbose_name='周边'),
        ),
    ]
