# Generated by Django 3.0.2 on 2020-01-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_hotelfacegroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='numer',
            new_name='number',
        ),
    ]
