# Generated by Django 3.0.2 on 2020-02-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_hotel_ambitus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
