# Generated by Django 3.0.2 on 2020-01-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200122_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_content',
            field=models.TextField(null=True, verbose_name='详细描述'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_name',
            field=models.CharField(max_length=50, null=True, verbose_name='房间类型名称'),
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
