# Generated by Django 3.0.2 on 2020-01-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200122_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type_content',
            field=models.TextField(null=True, verbose_name='房间类型详细描述'),
        ),
    ]
