# Generated by Django 3.0.2 on 2020-02-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200217_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='lat',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lon',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='经度'),
        ),
    ]
