# Generated by Django 3.0.2 on 2020-02-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200218_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambitus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='周边名称')),
                ('img', models.CharField(max_length=500, verbose_name='周边图片')),
                ('tabs', models.CharField(max_length=200, verbose_name='周边标签')),
                ('lat', models.CharField(max_length=30, verbose_name='周边经度')),
                ('lon', models.CharField(max_length=30, verbose_name='周边纬度')),
                ('city', models.CharField(max_length=20, verbose_name='周边所在城市')),
            ],
            options={
                'verbose_name': '周边',
                'verbose_name_plural': '周边',
                'db_table': 'ambitus',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'managed': False, 'verbose_name': '酒店管理', 'verbose_name_plural': '酒店管理'},
        ),
    ]
