# Generated by Django 3.0.2 on 2020-02-29 16:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('status', models.BooleanField(blank=True, null=True, verbose_name='阅读状态')),
                ('recID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('sendID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '站内信',
                'verbose_name_plural': '站内信',
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '信内容',
                'verbose_name_plural': '信内容',
                'db_table': 'message_text',
            },
        ),
        migrations.CreateModel(
            name='MessageSysStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('status', models.BooleanField(default=False, verbose_name='阅读状态')),
                ('RecID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msg.Messages', verbose_name='消息')),
            ],
            options={
                'verbose_name': '系统通知阅读状态',
                'verbose_name_plural': '系统通知阅读状态',
                'db_table': 'message_sys_status',
            },
        ),
        migrations.AddField(
            model_name='messages',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msg.MessageText', verbose_name='站内信消息'),
        ),
    ]
