# Generated by Django 3.0.2 on 2020-02-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagesysstatus',
            old_name='RecID',
            new_name='recID',
        ),
    ]
