# Generated by Django 3.0.2 on 2020-03-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_auto_20200229_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='extra',
            field=models.TextField(blank=True, null=True, verbose_name='额外字段'),
        ),
        migrations.AddField(
            model_name='messages',
            name='subtype',
            field=models.IntegerField(blank=True, null=True, verbose_name='消息子类型'),
        ),
        migrations.AddField(
            model_name='messages',
            name='type',
            field=models.IntegerField(choices=[(0, '系统消息'), (1, '私聊消息')], default=0, verbose_name='消息类型'),
        ),
    ]
