# Generated by Django 3.0.2 on 2020-03-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0003_auto_20200301_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='extra',
            field=models.TextField(blank=True, default='', null=True, verbose_name='额外字段'),
        ),
    ]
