# Generated by Django 3.0.2 on 2020-03-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0004_auto_20200301_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='subtype',
            field=models.IntegerField(default=0, verbose_name='消息子类型'),
        ),
    ]
