# Generated by Django 3.0.2 on 2020-03-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0005_auto_20200301_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='subtype',
            field=models.CharField(default='', max_length=50, verbose_name='消息子类型'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='type',
            field=models.CharField(choices=[('system', '系统消息'), ('private', '私聊消息')], default='', max_length=50, verbose_name='消息类型'),
        ),
    ]
