# Generated by Django 3.0.2 on 2020-03-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0006_auto_20200301_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='subtype',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='消息子类型'),
        ),
    ]
