# Generated by Django 3.0.2 on 2020-03-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0007_auto_20200301_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='type',
            field=models.CharField(default='', max_length=50, verbose_name='消息类型'),
        ),
    ]
