# Generated by Django 3.0.2 on 2020-03-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0008_auto_20200301_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='subtype',
            field=models.CharField(default='', max_length=50, verbose_name='消息子类型'),
        ),
    ]
