# Generated by Django 3.0.2 on 2020-01-23 19:07

import apps.faces.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='真实姓名')),
                ('sex', models.CharField(choices=[('male', '先生'), ('female', '女士')], max_length=6, null=True, verbose_name='性别')),
                ('content', models.CharField(default='', max_length=100, verbose_name='备注')),
                ('sign', models.TextField(verbose_name='特征值')),
                ('if_local', models.BooleanField(default=True, verbose_name='图片是否本地储存')),
                ('pic', models.ImageField(max_length=2048, upload_to='media', verbose_name='注册图片')),
                ('cos_pic', models.ImageField(max_length=1024, null=True, storage=apps.faces.models.CosStorage(path='facesdata'), upload_to='', verbose_name='COS注册图片')),
            ],
            options={
                'verbose_name': '人员数据',
                'verbose_name_plural': '人员数据',
                'db_table': 'faces',
            },
        ),
        migrations.CreateModel(
            name='FaceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='人员库名称')),
                ('content', models.TextField(verbose_name='人员库描述')),
            ],
            options={
                'verbose_name': '人员库',
                'verbose_name_plural': '人员库',
                'db_table': 'faces_group',
            },
        ),
        migrations.CreateModel(
            name='UserFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faces.FaceData', verbose_name='人脸数据')),
            ],
            options={
                'verbose_name': '用户 - 人脸',
                'verbose_name_plural': '用户 - 人脸',
                'db_table': 'user_face',
            },
        ),
    ]
