# Generated by Django 3.0.2 on 2020-01-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facegroup',
            name='group_content',
            field=models.TextField(verbose_name='人员库描述'),
        ),
    ]
