# Generated by Django 3.0.2 on 2020-01-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_auto_20200123_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facegroup',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='人员库名称'),
        ),
    ]
