# Generated by Django 3.0.2 on 2020-01-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0003_auto_20200123_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facegroup',
            name='content',
            field=models.TextField(null=True, verbose_name='人员库描述'),
        ),
    ]
