# Generated by Django 3.0.2 on 2020-01-16 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faces', '0001_initial'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device', verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='faces_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faces.FaceGroup', verbose_name='人员库'),
        ),
    ]
