# Generated by Django 3.0.2 on 2020-02-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('devices', '0003_auto_20200202_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Hotel', verbose_name='所属酒店'),
        ),
        migrations.DeleteModel(
            name='DeviceUser',
        ),
    ]
