# Generated by Django 3.0.2 on 2020-02-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20200202_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='是否在线'),
        ),
    ]
