# Generated by Django 3.0.2 on 2020-01-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realauth', '0002_auto_20200128_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realauth',
            name='organization',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='签发机关'),
        ),
    ]
