# Generated by Django 3.0.2 on 2020-02-19 16:28

import apps.pics.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PicBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('name', models.TextField(verbose_name='图片名称')),
                ('if_local', models.BooleanField(default=False, verbose_name='是否本地存储')),
                ('local_url', models.ImageField(blank=True, max_length=2048, null=True, upload_to='media', verbose_name='本地存储地址')),
                ('cos_url', models.ImageField(blank=True, max_length=2048, null=True, storage=apps.pics.models.CosStorage(''), upload_to='', verbose_name='COS存储地址')),
            ],
            options={
                'verbose_name': '图床',
                'verbose_name_plural': '图床',
                'db_table': 'picbed',
            },
        ),
    ]
