# Generated by Django 3.0.2 on 2020-02-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picbed',
            name='upload_to',
            field=models.TextField(default='', verbose_name='上传到'),
        ),
    ]
