# Generated by Django 3.0.2 on 2020-02-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_auto_20200219_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='picbed',
            name='content',
            field=models.TextField(default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='picbed',
            name='name',
            field=models.CharField(max_length=200, verbose_name='图片名称'),
        ),
    ]
