# Generated by Django 3.0.2 on 2020-02-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0004_auto_20200219_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picbed',
            name='content',
            field=models.TextField(default='', verbose_name='描述'),
        ),
    ]
