# Generated by Django 3.0.2 on 2020-02-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0005_auto_20200219_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='picbed',
            name='md5',
            field=models.CharField(default='', max_length=32, verbose_name='MD5'),
        ),
    ]
