# Generated by Django 3.0.2 on 2020-02-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0006_picbed_md5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picbed',
            name='content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='picbed',
            name='md5',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='MD5'),
        ),
    ]
