"""
Django settings for Hotel project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't8orzbrmu_&p0y8wru4_4*v+zpdt4h0h&j9c+9@61p6j^0eujy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["hotel.lcworkroom.cn", "lcworkroom.cn", "zustjinzhu.com", "127.0.0.1", "localhost", "192.168.1.104"]

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "apps.users.apps.UsersConfig",
    "apps.faces.apps.FacesConfig",
    "apps.tokens.apps.TokensConfig",
    "apps.devices.apps.DevicesConfig",
    "apps.rooms.apps.RoomsConfig",
    "apps.guests.apps.GuestsConfig",
    "apps.pics.apps.PicsConfig",
    "apps.customerserver.apps.CustomerserverConfig",
    "apps.realauth.apps.RealauthConfig",
    "apps.msg.apps.MsgConfig",
    "apps.locker.apps.LockerConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Hotel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Hotel.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'arcface',
        'USER': 'hotel',
        'PASSWORD': 'hotel2020',
        'HOST': '5780e03864e11.sh.cdb.myqcloud.com',
        'PORT': 4201,
    }
}

# Redis
REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB = 0
REDIS_PASS = "foobared"
REDIS_IMG_SETNAME = "img_authentication"
REDIS_SMS_SETNAME = "sms_authentication"

# SMS
SMS_APPID = "1400097031"
SMS_APPKEY = "417a2a23700289bf50f6cff4fdefa467"

# COS
COS_SECRET_ID = "AKIDBA5ss1AJZZloVP4la9SWpMC6wXtzqNfi"
COS_SECRET_KEY = "A9yjEUcmhMmaCYf3SjwyBSjZZUOAh0GW"
COS_REGION = "ap-shanghai"
COS_BUCKET = "hotel-1251848017"
COS_ALLOWURL = "http://127.0.0.1,http://localhost"
COS_ROOTURL = "https://hotel-1251848017.cos.ap-shanghai.myqcloud.com/"
COS_SERVER_MODE = 1
COS_CACHE_TIME = 3

# Arcface
ARCFACE_APPID = "6Tg7oTsTDnqP7N56RAvSzkQg3Xj3rjHvuwiuf3mKB2eJ"
ARCFACE_KEY_Win32 = "gpqGgwU7yKFCCRDCFVVFvm95xdfZndCTA6qDJJhoa1q"
ARCFACE_KEY_Win64 = "gpqGgwU7yKFCCRDCFVVFvm99CrteaKogj6Wynk8xh6R"
ARCFACE_KEY_Linux64 = "gpqGgwU7yKFCCRDCFVVFvm916HnJtCA4y8LDjU5rNTk"

# 讯飞
ITA_APPID = "5d3f1d27"
ITA_APIKEY = "eedaa8de4a740862728a90fe3e79aaea"
ITA_SECRET = "d045bf793b3d4d3adab55f27f876e0a9"

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

# simpleui
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'
# SIMPLEUI_HOME_PAGE = 'https://www.baidu.com'
# SIMPLEUI_HOME_TITLE = '酒店视觉AI解决方案-后台管理'
SIMPLEUI_HOME_INFO = False  # 服务器信息,右侧simple ui主页
SIMPLEUI_ANALYSIS = False

# HP-socket
HP_SOCKET_IP = "118.25.98.76"
HP_SOCKET_PORT = 9527
HP_SOCKET_FLAG = 1023
HP_SOCKET_MAXSIZE = 102400

# MAP
MAP_KEY = "d168a0f41ef102f0b8cd8a17dc83114d"
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

AUTH_USER_MODEL = "users.Users"
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# AUTH_USER_MODEL = "users.User"
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
MEDIA_ROOT = os.path.join(BASE_DIR, "media")  # 注意:这里配置os的时候,不像配置static的时候要[],这里不需要[]
MEDIA_URL = "/media/"
API_ROOT = 'api/'

APPEND_SLASH = True
