# Generated by Django 3.0.2 on 2020-03-18 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0006_auto_20200219_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerFace',
            fields=[
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ID', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='身份证ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(blank=True, choices=[('male', '先生'), ('female', '女士'), ('unknown', '未知')], max_length=7, null=True, verbose_name='性别')),
                ('sign', models.TextField(verbose_name='特征值')),
                ('mask', models.BooleanField(blank=True, null=True, verbose_name='脸部遮罩物')),
            ],
            options={
                'verbose_name': '客流人脸',
                'verbose_name_plural': '客流人脸',
                'db_table': 'passenger_face',
            },
        ),
        migrations.CreateModel(
            name='PassengerFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='进入时间')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='离开时间')),
                ('location', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='记录地点')),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passengerFlow.PassengerFace', verbose_name='客流人脸信息')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Hotel', verbose_name='记录酒店')),
            ],
            options={
                'verbose_name': '客流量',
                'verbose_name_plural': '客流量',
                'db_table': 'passenger_flow',
            },
        ),
    ]
