# Generated by Django 3.0.2 on 2020-03-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengerFlow', '0002_auto_20200318_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerface',
            name='num',
            field=models.IntegerField(default=1, verbose_name='出现次数'),
        ),
    ]
