# Generated by Django 3.0.2 on 2020-03-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengerFlow', '0003_passengerface_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerface',
            name='num',
            field=models.IntegerField(default=0, verbose_name='出现次数'),
        ),
    ]
