# Generated by Django 3.0.2 on 2020-01-10 21:22

import apps.users.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('realname', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('sign', models.CharField(max_length=1024, verbose_name='用户特征')),
                ('pic', models.ImageField(upload_to=apps.users.models.CosStorage(path='facedata'), verbose_name='用户特征影响')),
            ],
            options={
                'verbose_name': '人脸数据库',
                'verbose_name_plural': '人脸数据库',
                'db_table': 'faces',
            },
        ),
    ]
