# Generated by Django 3.0.2 on 2020-01-10 21:23

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='pic',
            field=models.ImageField(max_length=2048, upload_to=apps.users.models.CosStorage(path='facedata'), verbose_name='用户特征影响'),
        ),
    ]
