# Generated by Django 3.0.2 on 2020-01-10 21:59

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200110_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='pic',
            field=models.ImageField(max_length=2048, storage=apps.users.models.CosStorage(path='facedata'), upload_to='', verbose_name='用户特征影响'),
        ),
    ]
