# Generated by Django 3.0.2 on 2020-01-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200111_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facedata',
            name='id',
        ),
        migrations.AlterField(
            model_name='facedata',
            name='realname',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='真实姓名'),
        ),
    ]
