# Generated by Django 3.0.2 on 2020-01-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200111_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='pic',
            field=models.ImageField(max_length=2048, upload_to='media/', verbose_name='用户特征影响'),
        ),
    ]
