# Generated by Django 3.0.2 on 2020-01-23 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booking', '预订中'), ('checkin', '已登记入住'), ('checkout', '已退房')], default='booking', max_length=8, verbose_name='入住状态')),
                ('check_in_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='入住时间')),
                ('check_out_time', models.DateTimeField(null=True, verbose_name='退房时间')),
            ],
            options={
                'verbose_name': '来宾-房间',
                'verbose_name_plural': '来宾-房间',
                'db_table': 'guest_room',
            },
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ID', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.CharField(choices=[('male', '先生'), ('female', '女士')], max_length=6, verbose_name='性别')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '来宾',
                'verbose_name_plural': '来宾',
                'db_table': 'guests',
            },
        ),
        migrations.CreateModel(
            name='GuestVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='申请时间')),
                ('status', models.CharField(choices=[('applying', '申请中'), ('accept', '允许访问'), ('refuse', '拒绝访问')], default='applying', max_length=8, verbose_name='申请状态')),
                ('visitor_content', models.TextField(null=True, verbose_name='访客申请内容')),
                ('guest_content', models.TextField(null=True, verbose_name='来宾回复内容')),
            ],
            options={
                'verbose_name': '访客申请记录',
                'verbose_name_plural': '访客申请记录',
                'db_table': 'guest_visitor',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ID', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.CharField(choices=[('male', '先生'), ('female', '女士')], max_length=6, verbose_name='性别')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '访客',
                'verbose_name_plural': '访客',
                'db_table': 'visitors',
            },
        ),
    ]
