# Generated by Django 3.0.2 on 2020-01-21 00:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ID', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.CharField(choices=[('male', '先生'), ('female', '女士')], max_length=6, verbose_name='性别')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '来宾',
                'verbose_name_plural': '来宾',
                'db_table': 'guests',
            },
        ),
        migrations.CreateModel(
            name='GuestRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booking', '预订中'), ('checkin', '已登记入住'), ('checkout', '已退房')], default='booking', max_length=8, verbose_name='入住状态')),
                ('check_in_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='入住时间')),
                ('check_out_time', models.DateTimeField(null=True, verbose_name='退房时间')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Guests', verbose_name='来宾')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room', verbose_name='入住房间')),
            ],
            options={
                'verbose_name': '用户-房间',
                'verbose_name_plural': '用户-房间',
                'db_table': 'guest_room',
            },
        ),
    ]
