# Generated by Django 3.0.2 on 2020-01-26 15:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booking', '预订中'), ('checkin', '已登记入住'), ('checkout', '已退房')], default='booking', max_length=8, verbose_name='入住状态')),
                ('check_in_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='入住时间')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='退房时间')),
            ],
            options={
                'verbose_name': '来宾-房间',
                'verbose_name_plural': '来宾-房间',
                'db_table': 'guest_room',
            },
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '来宾',
                'verbose_name_plural': '来宾',
                'db_table': 'guests',
            },
        ),
        migrations.CreateModel(
            name='GuestVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='申请时间')),
                ('status', models.CharField(choices=[('applying', '申请中'), ('accept', '允许访问'), ('refuse', '拒绝访问')], default='applying', max_length=8, verbose_name='申请状态')),
                ('visitor_content', models.TextField(blank=True, null=True, verbose_name='访客申请内容')),
                ('guest_content', models.TextField(blank=True, null=True, verbose_name='来宾回复内容')),
            ],
            options={
                'verbose_name': '访客申请记录',
                'verbose_name_plural': '访客申请记录',
                'db_table': 'guest_visitor',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('real_auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realauth.RealAuth', verbose_name='实名认证库')),
            ],
            options={
                'verbose_name': '访客',
                'verbose_name_plural': '访客',
                'db_table': 'visitors',
            },
        ),
    ]
