# Generated by Django 3.0.2 on 2020-01-26 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realauth', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='guestvisitor',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Guests', verbose_name='来宾'),
        ),
        migrations.AddField(
            model_name='guestvisitor',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Visitor', verbose_name='访客'),
        ),
        migrations.AddField(
            model_name='guests',
            name='real_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realauth.RealAuth', verbose_name='实名认证库'),
        ),
        migrations.AddField(
            model_name='guests',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='guestroom',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Guests', verbose_name='来宾'),
        ),
        migrations.AddField(
            model_name='guestroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room', verbose_name='入住房间'),
        ),
    ]
