# Generated by Django 3.0.2 on 2020-01-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestroom',
            options={'verbose_name': '来宾-房间', 'verbose_name_plural': '来宾-房间'},
        ),
    ]
