# Generated by Django 3.0.2 on 2020-01-21 12:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guests', '0002_auto_20200121_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ID', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.CharField(choices=[('male', '先生'), ('female', '女士')], max_length=6, verbose_name='性别')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '访客',
                'verbose_name_plural': '访客',
                'db_table': 'visitors',
            },
        ),
        migrations.CreateModel(
            name='GuestVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='申请时间')),
                ('status', models.CharField(choices=[('applying', '申请中'), ('accept', '允许访问'), ('refuse', '拒绝访问')], default='applying', max_length=8, verbose_name='申请状态')),
                ('visitor_content', models.TextField(null=True, verbose_name='访客申请内容')),
                ('guest_content', models.TextField(null=True, verbose_name='来宾回复内容')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Guests', verbose_name='来宾')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Visitor', verbose_name='访客')),
            ],
            options={
                'verbose_name': '访客申请记录',
                'verbose_name_plural': '访客申请记录',
                'db_table': 'guest_visitor',
            },
        ),
    ]
