# Generated by Django 3.0.2 on 2020-02-18 19:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200218_1929'),
        ('guests', '0002_auto_20200126_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('days', models.IntegerField(verbose_name='预订天数')),
                ('totalprice', models.FloatField(verbose_name='总价')),
                ('date_start', models.DateTimeField(verbose_name='开始时间')),
                ('date_end', models.DateTimeField(verbose_name='结束时间')),
                ('guests', models.TextField(default='', verbose_name='住客')),
                ('status', models.IntegerField(default=0, max_length=3, verbose_name='订单状态')),
                ('pay_time', models.DateTimeField(verbose_name='支付时间')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Guests', verbose_name='预订人')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Hotel', verbose_name='酒店')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='guestroom',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guests.Orders', verbose_name='订单'),
        ),
    ]
