# Generated by Django 3.0.2 on 2020-02-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_auto_20200218_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestroom',
            options={'managed': False, 'verbose_name': '来宾-房间', 'verbose_name_plural': '来宾-房间'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': False, 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
    ]
