# Generated by Django 3.0.2 on 2020-03-10 11:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0006_auto_20200219_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('index', models.IntegerField(verbose_name='寄存柜序列')),
                ('num', models.IntegerField(verbose_name='储存柜号码')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Hotel', verbose_name='所处酒店')),
            ],
            options={
                'verbose_name': '寄存柜信息',
                'verbose_name_plural': '寄存柜信息',
                'db_table': 'locker',
            },
        ),
        migrations.CreateModel(
            name='LockerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('status', models.CharField(max_length=50, verbose_name='使用状态')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locker.Locker', verbose_name='寄存柜信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '寄存柜使用情况',
                'verbose_name_plural': '寄存柜使用情况',
                'db_table': 'locker_order',
            },
        ),
    ]
