# Generated by Django 3.0.2 on 2020-03-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='available',
            field=models.BooleanField(default=True, verbose_name='是否可用'),
        ),
        migrations.AddField(
            model_name='locker',
            name='used',
            field=models.BooleanField(default=False, verbose_name='是否被使用'),
        ),
        migrations.AlterField(
            model_name='lockerorder',
            name='status',
            field=models.CharField(choices=[('applying', '预约中'), ('using', '使用中'), ('canceled', '被取消'), ('done', '使用完成')], max_length=50, verbose_name='使用状态'),
        ),
    ]
