# Generated by Django 3.0.2 on 2020-03-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_auto_20200310_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='index',
            field=models.IntegerField(verbose_name='单元序列'),
        ),
        migrations.AlterField(
            model_name='locker',
            name='num',
            field=models.IntegerField(verbose_name='编号'),
        ),
    ]
