# Generated by Django 3.0.2 on 2020-03-10 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_auto_20200229_1612'),
        ('locker', '0005_lockerorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockerorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Orders', verbose_name='订单信息'),
        ),
    ]
